parameters:
- name: cxService
  type: string
  default: SAST-Bug

variables:
- name: debug
  value: true 
pool:
#    name: Default
     vmImage: 'ubuntu-20.04'
  
steps:
- script: |
    curl -L "https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz" -o "ScaResolver.tar.gz" && tar -vxzf ScaResolver.tar.gz && sudo mv ScaResolver /usr/local/bin && rm ScaResolver.tar.gz
- script: |
    sed -i s/LogsDirectory=logs/LogsDirectory=\\/home\\/vsts\\/reslogs/g Configuration.ini
    sed -i s/\;LogLevel=Information/LogLevel=Debug/g Configuration.ini    
    cat Configuration.ini
- script: |
    sudo mv Configuration.ini /usr/local/bin

- script: |
    ls -lart /usr/local/bin
    
- bash: echo '-s $(Build.SourcesDirectory) -n meinaral-app-pipeline -r $(Agent.BuildDirectory)'    
- task: Application security testing@2022
  displayName: 'Application security testing'
  inputs:
      projectName: meinaral-app-pipeline
      syncMode: true
      enableProxy: false
      enableSastScan: false
      enableDependencyScan: true
      dependencyServerURL: SCA-umesh
      dependencyAccessControlURL: 'https://platform.checkmarx.net'
      dependencyWebAppURL: 'https://sca.checkmarx.net'
      includeSource: false
      dependencyFolderExclusion: 'cvs,.svn,.hg,.git,.bzr,bin,obj,backup,.idea,node_modules'
      dependencyTenant: BP
      scaVulnerabilityThreshold: false
      pathToScaResolver: '/usr/local/bin'
      isEnableScaResolver: true
      scaResolverAddParameters: '-s $(Build.SourcesDirectory) -n meinaral-app-pipeline -r $(Agent.BuildDirectory)'
      scaHigh: ' '
      scaMedium: ' '
      scaLow: ' '
      scaTeam: 'CxServer/'

- script: |
    cat /home/vsts/reslogs/*