steps:
- task: checkmarx.cxsast.cx-scan-task.Application security testing@2021
  displayName: 'Application security testing'
  inputs:
    projectName: test
    CheckmarxService: 'SAST-Bug'    
    incScan: false    
    fullTeamName: "/CxServer"
    comment: '$(Build.SourceBranchName)'    
    enableProxy: false
    enableSastScan: true    
    enableDependencyScan: false
