steps:
- task: checkmarx.cxsast.cx-scan-task.Application security testing@2021
  displayName: 'Application security testing'
  inputs:
    projectName: test
    CheckmarxService: 'SAST-Bug'
    fullTeamName: /CxServer
    incScan: false
    projectName: '$(Build.Repository.Name)'
    fullTeamName: "/CxServer"
    comment: '$(Build.SourceBranchName)'
    CheckmarxService: 'SAST-Bug'
    enableProxy: false
    enableSastScan: true
    incScan: false
    enableDependencyScan: false