parameters:
- name: cxService
  type: string
  default: SAST-Bug

pool:
  name: Default
  
steps:
- task: checkmarx.cxsast.cx-scan-task.Application security testing@2021
  displayName: 'Application security testing'
  inputs:
    projectName: test
    CheckmarxService: ${{ parameters.cxService }}
    incScan: false    
    fullTeamName: "/CxServer"
    comment: '$(Build.SourceBranchName)'    
    enableProxy: false
    enableSastScan: true    
    enableDependencyScan: false
