trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'localhost/my-sample-image'
  imageTag: 'latest'
  dockerfilePath: 'Dockerfile.custom'

steps:
- task: Checkout@1

- script: |
    echo "Building Docker image using $DOCKERFILEPATH..."
    docker build -f "$DOCKERFILEPATH" -t "$IMAGENAME:$IMAGETAG" .
  displayName: 'Build Docker Image with Custom Dockerfile'
  env:
    DOCKERFILEPATH: $(dockerfilePath)
    IMAGENAME: $(imageName)
    IMAGETAG: $(imageTag)

- script: |
    echo "Running Docker image..."
    docker run --rm "$IMAGENAME:$IMAGETAG"
  displayName: 'Run Docker Image'
  env:
    IMAGENAME: $(imageName)
    IMAGETAG: $(imageTag)
